const TeamDomain = ['CORE TEAM', 'SENIOR ADVISORS', 'DEVELOPERS', 'DESIGNERS', 'CONTENT AND CREATIVE', 'MARKETING TEAM', 'EXTERNAL AFFAIRS', 'PUBLIC RELATION'];
const TeamMemberName = [
  {
    first: 'Akshat Jain',
    second: 'Pranav Mittal',
    third: 'Bisesh Agarwal',
    fourth: 'Atharva Bhatt',
    fifth: 'Yashank Aggarwal',
    sixth: 'Shivansh Dubey',
    seventh: 'Suhani Agrawal',
    eighth: 'Raghav Agrawal',
    ninth: 'Suryansh Singh',
    tenth: 'Akshit Singla',
    eleventh: 'Ayush Bemera',
    twelfth: 'Ankur Agrawal',
    thirteenth: 'Raina Jain'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Devi Tanuja Vasamsetty',
    second: 'Korivi Vedharshini',
    third: 'Riya Saini',
    fourth: 'Kalpit Adhao',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Shubhi Singh',
    second: 'Archit Soni',
    third: 'Pratishtha Dhiraj',
    fourth: 'Krishna Priya',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Nishant Gounder',
    second: 'Pushpam Berlia',
    third: 'Harsh Singh',
    fourth: 'Deependra Singh',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Ayushi Gupta',
    second: 'Ankit',
    third: 'Shreyansh Jain',
    fourth: 'Shubham Kumar',
    fifth: 'Mohit Singh',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Avinash Singh',
    second: 'Kuldeep Singh',
    third: 'Nikhil Kumar Singh',
    fourth: 'Bhavna Chavan',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const MemberImage = [
  {
    first: '/assets/TeamsSectionImages/Akshat jain.jpg',
    second: '/assets/TeamsSectionImages/Pranav_Mittal.jpg',
    third: '/assets/TeamsSectionImages/Bisesh Agarwal.jpg',
    fourth: '/assets/TeamsSectionImages/Atharva_Bhatt.jpg',
    fifth: '/assets/TeamsSectionImages/Yashank Aggarwal.webp',
    sixth: '/assets/TeamsSectionImages/Yashank Aggarwal.webp',
    seventh: '/assets/TeamsSectionImages/Suhani Agrawal.jpg',
    eighth: '/assets/TeamsSectionImages/Raghav Agrawal.jpg',
    ninth: '/assets/TeamsSectionImages/Suryansh Singh.png',
    tenth: '/assets/TeamsSectionImages/Akshit Singla.jpg',
    eleventh: '/assets/TeamsSectionImages/Bemera Ayush.PNG',
    twelfth: '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    thirteenth: '/assets/TeamsSectionImages/Raina Jain .jpg'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const Designation = [
  {
    first: 'Convener',
    second: 'General Secretary',
    third: 'Co-Convener',
    fourth: 'Joint Gen Secy',
    fifth: 'Joint Gen Secy',
    sixth: 'Tech Secy',
    seventh: 'Tech Secy',
    eighth: 'Cult Secy',
    ninth: 'Cult Secy',
    tenth: 'Sports Secy',
    eleventh: 'Sports Secy',
    twelfth: 'Web Head',
    thirteenth: 'Web Head'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: ''
  },
  {
    first: 'Head',
    second: 'Coordinator',
    third: 'Coordinator',
    fourth: 'Coordinator',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Head',
    second: 'Coordinator',
    third: 'Coordinator',
    fourth: 'Coordinator',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Head',
    second: 'Coordinator',
    third: 'Coordinator',
    fourth: 'Coordinator',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Head',
    second: 'Head',
    third: 'Coordinator',
    fourth: 'Coordinator',
    fifth: 'Coordinator',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'Head',
    second: 'Coordinator',
    third: 'Coordinator',
    fourth: 'Coordinator',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const TeamMemberDetails = [
  {
    first: 'Akshat Jain',
    second: 'Pranav Mittal',
    third: 'Bisesh Agarwal',
    fourth: 'Atharva Bhatt',
    fifth: 'Yashank Aggarwal',
    sixth: 'Shivansh Dubey',
    seventh: 'Suhani Agrawal',
    eighth: 'Raghav Agrawal',
    ninth: 'Suryansh Singh',
    tenth: 'Akshit Singla',
    eleventh: 'Ayush Bemera',
    twelfth: 'Ankur Agrawal',
    thirteenth: 'Raina Jain'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const ContactMail = [
  {
    first: 'akshat.rajkumarjain.ece19@itbhu.ac.in',
    second: 'pranav.mittal.ece19@itbhu.ac.in',
    third: 'bisesh.agarwal.ece20@itbhu.ac.in',
    fourth: 'atharva.bhatt.ece20@itbhu.ac.in',
    fifth: 'yashank.aggarwal.ece20@itbhu.ac.in',
    sixth: 'shivansh.dubey.ece20@itbhu.ac.in',
    seventh: 'suhani.agrawal.ece20@itbhu.ac.in',
    eighth: 'raghav.agrawal.cd.ece20@itbhu.ac.in',
    ninth: 'suryansh.singh.cd.ece20@itbhu.ac.in',
    tenth: 'akshit.singla.ece20@itbhu.ac.in',
    eleventh: 'bemera.ayush.ece20@itbhu.ac.in',
    twelfth: 'ankur.agrawal.ece20@itbhu.ac.in',
    thirteenth: 'raina.jain.ece20@itbhu.ac.in'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: ' dtanuja.vasamsetty.ece20@itbhu.ac.in',
    second: 'korivi.vedharshini.ece20@itbhu.ac.in',
    third: 'riya.saini.ece20@itbhu.ac.in',
    fourth: 'kalpit.adhao.ece20@itbhu.ac.in',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'shubhi.singh.ece20@itbhu.ac.in',
    second: 'archit.soni.ece20@itbhu.ac.in',
    third: 'pratishtha.dhiraj.ece20@itbhu.ac.in',
    fourth: 'potnuru.vkrishnapriya.ece20@itbhu.ac.in',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'nishanth.gounder.ece20@itbhu.ac.in',
    second: 'pushpam.berlia.ece20@itbhu.ac.in',
    third: 'harsh.singh.ece20@itbhu.ac.in',
    fourth: 'deependra.singh.ece20@itbhu.ac.in',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'ayushi.gupta.ece20@itbhu.ac.in',
    second: 'ankit.student.ece20@itbhu.ac.in',
    third: 'shreyansh.jain.ece20@itbhu.ac.in',
    fourth: 'shubhamk.ece20@itbhu.ac.in',
    fifth: 'mohit.singh.cd.ece20@itbhu.ac.in',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: 'avinash.singh.ece20@itbhu.ac.in',
    second: ' kuldeep.singh.ece20@itbhu.ac.in',
    third: 'nikhil.kumarsingh.cd.ece20@itbhu.ac.in',
    fourth: 'bhavna.student.ece20@itbhu.ac.in',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const ContactInstagram = [
  {
    first: 'Akshat Jain',
    second: 'Pranav Mittal',
    third: 'Bisesh Agarwal',
    fourth: 'Atharva Bhatt',
    fifth: 'Yashank Aggarwal',
    sixth: 'Shivansh Dubey',
    seventh: 'Suhani Agrawal',
    eighth: 'Raghav Agrawal',
    ninth: 'Suryansh Singh',
    tenth: 'Akshit Singla',
    eleventh: 'Ayush Bemera',
    twelfth: 'Ankur Agrawal',
    thirteenth: 'Raina Jain'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
const ContactLinkedIn = [
  {
    first: 'Akshat Jain',
    second: 'Pranav Mittal',
    third: 'Bisesh Agarwal',
    fourth: 'Atharva Bhatt',
    fifth: 'Yashank Aggarwal',
    sixth: 'Shivansh Dubey',
    seventh: 'Suhani Agrawal',
    eighth: 'Raghav Agrawal',
    ninth: 'Suryansh Singh',
    tenth: 'Akshit Singla',
    eleventh: 'Ayush Bemera',
    twelfth: 'Ankur Agrawal',
    thirteenth: 'Raina Jain'
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  },
  {
    first: '',
    second: '',
    third: '',
    fourth: '',
    fifth: '',
    sixth: '',
    seventh: '',
    eighth: '',
    ninth: '',
    tenth: '',
    eleventh: '',
    twelfth: '',
    thirteenth: ''
  }
];
export { TeamMemberName, TeamDomain, Designation, TeamMemberDetails, ContactMail, ContactInstagram, ContactLinkedIn, MemberImage };
