const TeamDomain = ['CORE TEAM', 'SENIOR ADVISORS', 'DEVELOPERS', 'DESIGNERS', 'CONTENT AND CREATIVE', 'MARKETING TEAM', 'EXTERNAL AFFAIRS', 'PUBLIC RELATION'];
const TeamMemberName = [
  ['Akshat Jain', 'Pranav Mittal', 'Bisesh Agarwal', 'Atharva Bhatt', 'Yashank Aggarwal', 'Shivansh Dubey', 'Suhani Agrawal', 'Raghav Agrawal', 'Suryansh Singh', 'Akshit Singla', 'Ayush Bemera', 'Ankur Agrawal', 'Raina Jain', 'Nishant Gounder'],
  ['Yash Jain', 'Vikash Prajapati'],
  ['Ankur Agrawal', 'Raina Jain', 'Akash Kumar', 'Avnesh Kumar', 'Kumar Sonu', 'Dhruv Chaudhary', 'Anant Jain', 'MD Athar'],
  ['Devi Tanuja Vasamsetty', 'Korivi Vedharshini', 'Riya Saini', 'Kalpit Adhao'],
  ['Shubhi Singh', 'Archit Soni', 'Pratishtha Dhiraj', 'P V Krishna Priya', 'Tarun Siddharth', 'Sakshi Tomar', 'Anusha Mahajan', 'Ritesh Lakra', 'Dharmesh Mahajan', 'Shrirang Gupta', 'Avani Jangid', 'Saket Kumar Singh'],
  ['Nishant Gounder', 'Pushpam Berlia', 'Harsh Singh', 'Deependra Singh'],
  ['Ayushi Gupta', 'Ankit', 'Shreyansh Jain', 'Shubham Kumar', 'Mohit Singh', 'Riya Chauhan', 'Amit Kumar', 'Harsh Kumar', 'Aditya Mishra', 'Anshu Soni', 'Shivam Raj', 'Harsh Saini', 'Shivom', 'Vaatsalya Sinha', 'Nikhil Aggarwal'],
  ['Avinash Singh', 'Kuldeep Singh', 'Nikhil Kumar Singh', 'Bhavna Chavan', 'Priyanshu', 'Divyanshu', 'Ravi Kumar Meena', 'Jaya Kedia', 'Anupam Shukla', 'Vaibhav Gupta', 'Harshit Anand', 'Anshu Kumar', 'Utkarsh Kumar', 'Aditya chandel', 'Aditya kumar', 'Mendapara Khelankumar']
];
const MemberImage = [
  [
    '/assets/TeamsSectionImages/Akshat jain.jpg',
    '/assets/TeamsSectionImages/Pranav_Mittal.jpg',
    '/assets/TeamsSectionImages/Bisesh Agarwal.jpg',
    '/assets/TeamsSectionImages/Atharva_Bhatt.jpg',
    '/assets/TeamsSectionImages/Yashank Aggarwal.webp',
    '/assets/TeamsSectionImages/Shivansh_Dubey.jpg',
    '/assets/TeamsSectionImages/Suhani Agrawal.jpeg',
    '/assets/TeamsSectionImages/Raghav Agrawal.jpg',
    '/assets/TeamsSectionImages/Suryansh Singh.png',
    '/assets/TeamsSectionImages/Akshit Singla.jpg',
    '/assets/TeamsSectionImages/Bemera Ayush.PNG',
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Raina Jain.jpg',
    '/assets/TeamsSectionImages/Nishanth Gounder.jpg'
  ],
  ['/assets/TeamsSectionImages/Yash_Jain.jpg', '/assets/TeamsSectionImages/Vikash_Prajapati.jpg'],
  ['/assets/TeamsSectionImages/Ankur Agarwal.jpg', '/assets/TeamsSectionImages/Raina Jain.jpg', '/assets/TeamsSectionImages/Akash_Kumar.jpg', '/assets/TeamsSectionImages/Avnesh kumar.jpg', '/assets/TeamsSectionImages/Ankur Agarwal.jpg', '/assets/TeamsSectionImages/Dhruv Chaudhary.jpg', '/assets/TeamsSectionImages/Anant Jain.jpg', '/assets/TeamsSectionImages/Md_Athar.jpg'],
  ['/assets/TeamsSectionImages/Devi_Tanuja_Vasamsetty.jpg', '/assets/TeamsSectionImages/Korivi Vedharshini.jpg', '/assets/TeamsSectionImages/Riya Saini.jpg', '/assets/TeamsSectionImages/Kalpit Adhao.jpg'],
  [
    '/assets/TeamsSectionImages/Shubhi Singh.jpg',
    '/assets/TeamsSectionImages/Archit Soni.jpg',
    '/assets/TeamsSectionImages/Pratistha Dhiraj.jpg',
    '/assets/TeamsSectionImages/P V Krishna Priya.jpg',
    '/assets/TeamsSectionImages/Tarun Siddharth.jpeg',
    '/assets/TeamsSectionImages/Sakshi Tomar.jpg',
    '/assets/TeamsSectionImages/Anusha Mahajan.jpg',
    '/assets/TeamsSectionImages/Ritesh Lakra.jpeg',
    '/assets/TeamsSectionImages/Dharmesh Mahajan.jpg',
    '/assets/TeamsSectionImages/Shrirang Gupta.jpeg',
    '/assets/TeamsSectionImages/Avani Jangid.jpeg',
    '/assets/TeamsSectionImages/Saket Kumar Singh.jpg'
  ],
  ['/assets/TeamsSectionImages/Nishanth Gounder.jpg', '/assets/TeamsSectionImages/Pushpam Berlia.jpg', '/assets/TeamsSectionImages/Harsh Singh.jpg', '/assets/TeamsSectionImages/Deependra Singh.jpg'],
  [
    '/assets/TeamsSectionImages/Ayushi Gupta.jpg',
    '/assets/TeamsSectionImages/Ankit.jpg',
    '/assets/TeamsSectionImages/Shreyansh Jain.jpg',
    '/assets/TeamsSectionImages/Shubham Kumar.jpeg',
    '/assets/TeamsSectionImages/Mohit Singh.jpg',
    '/assets/TeamsSectionImages/Riya Chauhan.jpg',
    '/assets/TeamsSectionImages/Amit Kumar.jpg',
    '/assets/TeamsSectionImages/Harsh Kumar.jpg',
    '/assets/TeamsSectionImages/Aditya Mishra.jpeg',
    '/assets/TeamsSectionImages/Anshu Soni.jpg',
    '/assets/TeamsSectionImages/Shivam Raj.jpg',
    '/assets/TeamsSectionImages/Harsh Saini.jpg',
    '/assets/TeamsSectionImages/Shivom.jpg',
    '/assets/TeamsSectionImages/Vaatsalya Sinha.jpg',
    '/assets/TeamsSectionImages/Nikhil Aggarwal.jpeg'
  ],
  [
    '/assets/TeamsSectionImages/Avinash Singh.jpeg',
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Ankur Agarwal.jpg',
    '/assets/TeamsSectionImages/Priyanshu.jpg',
    '/assets/TeamsSectionImages/Divyanshu Devashish.jpg',
    '/assets/TeamsSectionImages/Ravi Kumar Meena.jpg',
    '/assets/TeamsSectionImages/Jaya Kedia.jpg',
    '/assets/TeamsSectionImages/Anupam Shukla.jpg',
    '/assets/TeamsSectionImages/Vaibhav Gupta.jpg',
    '/assets/TeamsSectionImages/Harshit Anand.jpg',
    '/assets/TeamsSectionImages/Anshu Kumar.jpg',
    '/assets/TeamsSectionImages/Utkarsh Kumar.jpg',
    '/assets/TeamsSectionImages/Aditya Chandel.jpg',
    '/assets/TeamsSectionImages/Aditya Kumar.jpg',
    '/assets/TeamsSectionImages/Khelan Kumar.jpg'
  ]
];
const Designation = [
  ['Convener', 'General Secretary', 'Co-Convener', 'Joint Gen Secy', 'Joint Gen Secy', 'Tech Secy', 'Tech Secy', 'Cult Secy', 'Cult Secy', 'Sports Secy', 'Sports Secy', 'Web Head', 'Web Head', 'Marketing Head'],
  ['Senior web advisor', 'Senior Advisor External Affairs'],
  ['Web Head', 'Web Head', 'Backend Developer', 'Frontend Developer', 'Frontend Developer', 'Frontend Developer', 'Frontend Developer', 'Frontend Developer'],
  ['Head', 'Coordinator', 'Coordinator', 'Coordinator'],
  ['Content Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator'],
  ['Marketing Head', 'Coordinator', 'Coordinator', 'Coordinator'],
  ['Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator'],
  ['Head', 'Coordinator', 'Coordinator', 'Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator', 'Co-Coordinator']
];
const TeamMemberDetails = [
  ['Fourth Yearite', 'Fourth Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite'],
  ['Fourth Yearite', 'Fourth Yearite'],
  ['Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite'],
  ['Third Yearite', 'Third Yearite', 'Third Yearite', 'Third Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite', 'Second Yearite']
];
const ContactMail = [
  [
    'akshat.rajkumarjain.ece19@itbhu.ac.in',
    'pranav.mittal.ece19@itbhu.ac.in',
    'bisesh.agarwal.ece20@itbhu.ac.in',
    'atharva.bhatt.ece20@itbhu.ac.in',
    'yashank.aggarwal.ece20@itbhu.ac.in',
    'shivansh.dubey.ece20@itbhu.ac.in',
    'suhani.agrawal.ece20@itbhu.ac.in',
    'raghav.agrawal.cd.ece20@itbhu.ac.in',
    'suryansh.singh.cd.ece20@itbhu.ac.in',
    'akshit.singla.ece20@itbhu.ac.in',
    'bemera.ayush.ece20@itbhu.ac.in',
    'ankur.agrawal.ece20@itbhu.ac.in',
    'raina.jain.ece20@itbhu.ac.in',
    'nishanth.gounder.ece20@itbhu.ac.in'
  ],
  ['yash.jain.ece19@itbhu.ac.in', 'vikash.prajapati.ece19@itbhu.ac.in'],
  ['ankur.agrawal.ece20@itbhu.ac.in', 'raina.jain.ece20@itbhu.ac.in', 'akash.kumar.ece21@itbhu.ac.in', 'avnesh.kumar.ece21@itbhu.ac.in', 'kumar.sonu.ece21@itbhu.ac.in', 'dhruv.chaudhary.ece21@itbhu.ac.in', 'anant.jain.ece21@itbhu.ac.in', 'md.athar.ece21@itbhu.ac.in'],
  ['dtanuja.vasamsetty.ece20@itbhu.ac.in', 'korivi.vedharshini.ece20@itbhu.ac.in', 'riya.saini.ece20@itbhu.ac.in', 'kalpit.adhao.ece20@itbhu.ac.in'],
  [
    'shubhi.singh.ece20@itbhu.ac.in',
    'archit.soni.ece20@itbhu.ac.in',
    'pratishtha.dhiraj.ece20@itbhu.ac.in',
    'potnuru.vkrishnapriya.ece20@itbhu.ac.in',
    'starun.siddharth.ece21@itbhu.ac.in',
    'sakshi.tomar.ece21@itbhu.ac.in',
    'anusha.mahajan.ece21@itbhu.ac.in',
    'ritesh.lakra.ece21@itbhu.ac.in',
    'dharmesh.mahajan.ece21@itbhu.ac.in',
    'sbrajesh.gupta.ece21@itbhu.ac.in',
    'avani.jangid.cd.ece21@itbhu.ac.in',
    'saket.kumarsingh.ece21@itbhu.ac.in'
  ],
  ['nishanth.gounder.ece20@itbhu.ac.in', 'pushpam.berlia.ece20@itbhu.ac.in', 'harsh.singh.ece20@itbhu.ac.in', 'deependra.singh.ece20@itbhu.ac.in'],
  [
    'ayushi.gupta.ece20@itbhu.ac.in',
    'ankit.student.ece20@itbhu.ac.in',
    'shreyansh.jain.ece20@itbhu.ac.in',
    'shubhamk.ece20@itbhu.ac.in',
    'mohit.singh.cd.ece20@itbhu.ac.in',
    'riya.chauhan.ece21@itbhu.ac.in',
    'amit.kumar.ece21@itbhu.ac.in',
    'harsh.kumar.ece21@itbhu.ac.in',
    'aditya.mishra.ece21@itbhu.ac.in',
    'anshu.soni.ece21@iitbhu.ac.in',
    'shivam.raj.ece21@itbhu.ac.in',
    'harsh.saini.ece21@itbhu.ac.in',
    'shivom.student.ece21@itbhu.ac.in',
    'vaatsalya.sinha.ece21@itbhu.ac.in',
    'nikhil.aggarwa.ece21@itbhu.ac.in'
  ],
  [
    'avinash.singh.ece20@itbhu.ac.in',
    'kuldeep.singh.ece20@itbhu.ac.in',
    'nikhil.kumarsingh.cd.ece20@itbhu.ac.in',
    'bhavna.student.ece20@itbhu.ac.in',
    'priyanshu.student.ece21@itbhu.ac.in',
    'divyanshu.student.ece21@itbhu.ac.in',
    'ravikumar.meena.ece21@itbhu.ac.in',
    'jaya.kedia.cd.ece21@itbhu.ac.in',
    'anupam.shukla.ece21@itbhu.ac.in',
    'vaibhav.gupta.ece21@itbhu.ac.in',
    'harshit.anand.ece21@itbhu.ac.in',
    'anshu.kumar.ece21@itbhu.ac.in',
    'utkarsh.kumar.ece21@itbhu.ac.in',
    'aditya.chandel.ece21@itbhu.ac.in',
    'aditya.kumar.ece21@itbhu.ac.in',
    'mkhelank.hasmukhbhai.ece21@itbhu.ac.in'
  ]
];
const ContactInstagram = [
  [
    '',
    'https://www.instagram.com/pranav_2x1/',
    '',
    'https://instagram.com/bhattatharva?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/yashankagg?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/shivansh_d_/',
    'https://www.instagram.com/suhanii_97/?igshid=ZDdkNTZiNTM%3D',
    'https://www.instagram.com/ag_raghav26/',
    'https://instagram.com/_surya__ss?igshid=ZDdkNTZiNTM=',
    '',
    '',
    '',
    'https://www.instagram.com/raina_jainn/',
    'https://www.instagram.com/nishu_07.02/'
  ],
  ['https://instagram.com/yashjain484?igshid=ZDdkNTZiNTM=', 'https://instagram.com/vikash_0307?igshid=ZDdkNTZiNTM='],
  ['', 'https://www.instagram.com/raina_jainn/', 'https://instagram.com/akash_kourav03?igshid=ZDdkNTZiNTM=', 'https://instagram.com/avnesh141?igshid=ZDdkNTZiNTM=', '', 'https://www.instagram.com/dhruv_chaudhary_1380/', 'https://www.instagram.com/anant_jain_01/', 'https://www.instagram.com/mdathar44__/'],
  ['https://instagram.com/tanuja_winniee?igshid=ZDdkNTZiNTM=', 'https://instagram.com/vedharshinikorivi?igshid=ZDdkNTZiNTM=', 'https://instagram.com/r.i.y.a_s.a.i.n.i?igshid=ZDdkNTZiNTM=', 'https://instagram.com/kalpit_adhao?igshid=ZDdkNTZiNTM='],
  [
    '',
    'https://www.instagram.com/archit_soni3/',
    'https://instagram.com/pratishtha_dhiraj_?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/krishnapriya_213?r=nametag',
    'https://instagram.com/starun_siddharth?igshid=NTdlMDg3MTY=',
    'https://instagram.com/sksh.06?igshid=ZDdkNTZiNTM=',
    'http://instagram.com/anusha_mahajan4',
    'https://www.instagram.com/riteshlakra270419/',
    'https://instagram.com/dharmeshmahajan_',
    'https://www.instagram.com/gigamiles/',
    'https://instagram.com/theavanijangid?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/saketkr02?igshid=ZDdkNTZiNTM='
  ],
  ['https://www.instagram.com/nishu_07.02/', 'https://instagram.com/pushpamberlia?igshid=ZDdkNTZiNTM=', 'https://www.instagram.com/singh_harsh1608/', 'https://www.instagram.com/deependrasingh1037/'],
  [
    'https://instagram.com/ayushigupta400?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/ank.it7410?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/shreyanssshhh?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/ig_kshubham/',
    'https://www.instagram.com/01_mohit_02/',
    'https://www.instagram.com/_riyachauhan_09/',
    'https://instagram.com/1310amit21?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/_harsh.1510_/',
    'https://instagram.com/iaditya1441?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/',
    'https://instagram.com/shivamraj0812?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/sainiharsh2908?igshid=MDE2OWE1N2Q=',
    'https://instagram.com/shivom6516?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/vaatsalya_sinha/',
    'https://www.instagram.com/nikhilaggarwal.__/'
  ],
  [
    'http://www.instagram.com/avinash.singh___',
    '',
    '',
    '',
    'instagram.com/messy.medulla',
    'https://instagram.com/divyanshudevashish007?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/ravi_kumar.5/',
    'https://instagram.com/__.jaya.__1?igshid=YmMyMTA2M2Y=',
    'https://instagram.com/inikhil.shukla?igshid=ZDdkNTZiNTM=',
    'instagram.com/vaibhav_gupta00/',
    'https://instagram.com/harshitanand543?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/anshukumar613?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/utkarshkumar83958?igshid=ZDdkNTZiNTM=',
    'https://instagram.com/chande6526?igshid=ZDdkNTZiNTM=',

    'https://instagram.com/aadix__12?igshid=ZDdkNTZiNTM=',
    'https://www.instagram.com/kp_obviouslyop/'
  ]
];
const ContactLinkedIn = [
  [
    '',
    'https://www.linkedin.com/in/pranav-mittal-4b15a0195',
    '',
    'https://www.linkedin.com/in/atharva-bhatt-199665156',
    'https://www.linkedin.com/in/yashank-aggarwal-575750208',
    'https://www.linkedin.com/in/shivansh-dubey-032916213/',
    'https://www.linkedin.com/in/suhani-agrawal-4030861bb/',
    'https://www.linkedin.com/in/ag-raghav26/',
    'https://www.linkedin.com/in/suryansh-singh-5b89461bb',
    '',
    '',
    '',
    'https://www.linkedin.com/in/raina-jain-6b4b68143/',
    'https://www.linkedin.com/in/nishanth-gounder-15477a224/'
  ],
  ['https://www.linkedin.com/in/yash-jain-780332208', 'https://www.linkedin.com/in/vikash-prajapati-a82ba01b0'],
  ['', 'https://www.linkedin.com/in/raina-jain-6b4b68143/', 'https://www.linkedin.com/in/akash-kumar-371439246', 'https://www.linkedin.com/in/avnesh-kumar-08b549230', '', 'https://www.linkedin.com/in/dhruv-chaudhary-4b6179233', 'https://www.linkedin.com/in/anant-jain-8255a022b/', 'https://www.linkedin.com/in/md-athar4403/'],
  ['https://www.linkedin.com/in/devi-tanuja-vasamsetty-34b811218', 'https://www.linkedin.com/in/vedharshini-korivi-060317224', 'https://www.linkedin.com/in/riya-saini-ba7928229', 'https://www.linkedin.com/in/kalpit-adhao-6a4a25206'],
  [
    'https://www.linkedin.com/in/shubhi-singh-b13aba220',
    'https://www.linkedin.com/in/archit-soni/',
    'https://www.linkedin.com/in/pratishtha-dhiraj-113754215',
    'https://www.linkedin.com/in/krishna-priya-p-1966b8224',
    'https://www.linkedin.com/in/tarun-siddharth-46a126235',
    'https://www.linkedin.com/in/sakshi-tomar-376581230',
    'https://www.linkedin.com/in/anusha-mahajan-136771194',
    'https://www.linkedin.com/in/ritesh-lakra-8128b7242?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BzAPoo0mUQryReB%2FNZkis4Q%3D%3D',
    'https://www.linkedin.com/in/dharmesh-mahajan-23574a223',
    'https://www.linkedin.com/in/shrirang-gupta-887383263/',
    'https://www.linkedin.com/in/avani-jangid-307564229',
    'https://www.linkedin.com/in/saket-kumar-singh-b35b39222'
  ],
  ['https://www.linkedin.com/in/nishanth-gounder-15477a224/', 'https://www.linkedin.com/in/pushpam-berlia-89867b224', 'https://www.linkedin.com/in/harsh-singh-952a42217/', 'https://www.linkedin.com/in/deependra-singh-41943715a'],
  [
    'https://www.linkedin.com/in/ayushi-gupta-125082212',
    'https://www.linkedin.com/in/ankit-kumar-252ab7222',
    'https://www.linkedin.com/in/shreyansh-jain-964357227',
    'https://www.linkedin.com/in/kshubham01/',
    'https://www.linkedin.com/in/mohit-singh-8a4628208/',
    'https://www.linkedin.com/in/riya-chauhan-867592230/',
    'https://www.linkedin.com/in/amit-kumar-4-year-b-tech-electronics-engineering-a02508230',
    'https://www.linkedin.com/mwlite/in/harsh-kumar-ba799925b',
    'https://www.linkedin.com/in/aditya-mishra-8064481b8',
    'https://www.linkedin.com/in/anshu-soni-3975a0229',
    'https://www.linkedin.com/in/shivam-raj-892233243',
    'https://www.linkedin.com/in/harsh-saini-092353230/',
    'https://www.linkedin.com/in/shivom-387607224',
    'https://www.linkedin.com/in/ vaatsalya-sinha-4-year-b-tech-electronics-engineering-887752263',
    'https://www.linkedin.com/in/nikhil-aggarwal-92819b235/'
  ],
  [
    'https://www.linkedin.com/in/avinash-singh-a03b86224',
    '',
    '',
    '',
    'https://www.linkedin.com/mwlite/in/paloxzz',
    'https://www.linkedin.com/in/divyanshu-devashish-186579230',
    'https://www.linkedin.com/in/ravi-kumar-meena-868150245/',
    'https://www.linkedin.com/in/jaya-kedia-4b6805235',
    'https://www.linkedin.com/in/anupam-shukla-888315257',
    'https://www.linkedin.com/in/vaibhav-gupta-53b0bb227',
    'https://www.linkedin.com/in/harshit-anand-5856b4239',
    'https://www.linkedin.com/in/anshu-k-0425b5227',
    'https://www.linkedin.com/in/utkarsh-kumar-4-year-b-tech-electronics-engineering-6b2564230',
    'https://www.linkedin.com/in/aditya-chandel-4-year-b-tech-electronics-engineering-874a3425b',
    'https://www.linkedin.com/in/aditya-kumar-a445a0223',
    'https://www.linkedin.com/in/khelan-mendapara-11736b223'
  ]
];
export { TeamMemberName, TeamDomain, Designation, TeamMemberDetails, ContactMail, ContactInstagram, ContactLinkedIn, MemberImage };
